# - - - Config File Start - - -


# Site Customizations

title: Garrett Hubbs
description: About Me
logo: https://raw.githubusercontent.com/hubbsg/hubbsg.github.io/master/logo.PNG

# For Jekyll

theme: jekyll-theme-minimal
