# - - - Config File Start - - -


# Site Customizations

title: Garrett Hubbs
description: About Me

# For Jekyll

remote_theme: "mmistakes/minimal-mistakes@4.19.1"

plugins:
  - jekyll-include-cache
