# - - - Config File Start - - -


# Site Customizations

title: Garrett Hubbs
descriptions: About Me

github:
  is_project_page: false

# For Jekyll

theme: jekyll-theme-minimal

plugins:
  - jekyll-include-cache
