# - - - Config File Start - - -


# Site Customizations

title: Garrett Hubbs
logo: https://raw.githubusercontent.com/hubbsg/hubbsg.github.io/master/logo.PNG

# For Jekyll

theme: jekyll-theme-minimal
